#!/usr/bin/env python

Import("env")

env_jolt = env.Clone()

# To build Jolt, for now: (with gcc, for example)
#   $ cd joltphysics/Build
#   $ ./cmake_linux_clang_gcc.sh Debug g++
#   $ cd Linux_Debug
#   $ make -j 8

# include dirs
env_jolt.Append(CPPPATH=["#modules/jolt/joltphysics"])

# this folder should contain libJolt.a
# it is appended to the global env, not env_jolt
env.Append(LIBPATH=["#modules/jolt/joltphysics/Build/Linux_Debug"])
env.Append(LIBS=["Jolt"])

# source files
env_jolt.add_source_files(env_jolt.modules_sources, "*.cpp")

# Jolt has some comments ending in backslash
env_jolt.Append(CCFLAGS=["-Wno-comment"])

# For compatibility with debug binaries
env_jolt.Append(CPPDEFINES=["JPH_PROFILE_ENABLED", "JPH_ENABLE_ASSERTS"])

